FROM debian:bookworm-20240110
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y && \
    apt install curl unzip && \
    curl -O https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip && \
    unzip terraform_1.7.4_linux_amd64.zip && \
    mv terraform /usr/local/bin

COPY conf/ [tbd]