FROM nextcloud:30.0.4-fpm-alpine

RUN touch /usr/local/etc/php/conf.d/redis-session.ini && chown 0:33 /usr/local/etc/php/conf.d/redis-session.ini && chmod 770 /usr/local/etc/php/conf.d/redis-session.ini