FROM debian:bookworm-20240110
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y && \
    apt install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    lib32gcc-s1 \
    curl \
    locales && \
    adduser --disabled-password --gecos "" steam && \
    su steam -c 'cd && \
        mkdir -p /home/steam/steamcmd && \
        cd /home/steam/steamcmd && \
        curl -o steamcmd_linux.tar.gz "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" && \
        tar zxf steamcmd_linux.tar.gz && \
        rm steamcmd_linux.tar.gz' && \
    apt remove --purge -y curl && \
    apt autoremove -y && \
    cd /home/steam/steamcmd && \
    su steam -c "./steamcmd.sh +force_install_dir /home/steam/steamcmd/sandstorm/ +login anonymous +app_update 581330 validate +quit" && \
    mkdir -p "/home/steam/steamcmd/sandstorm/Insurgency/Saved/SaveGames"

WORKDIR /home/steam/steamcmd
USER steam

ENTRYPOINT /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/steamcmd/sandstorm/ +login anonymous +app_update 581330 +quit && \
           /home/steam/steamcmd/sandstorm/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping -MapCycle=MapCycle.txt -Mods -ModList=Mods.txt -mutators=$MUTATORS -ModDownloadTravelTo=$SCENARIO -hostname="$HOSTNAME" -Port=$PORT -QueryPort=$QUERYPORT