apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: gomplate
spec:
  version: v1.0
  discover:
    # Look for a gomplate.yaml data file which indicates this repo uses gomplate templating
    find:
      command:
        - sh
        - -c
        - |
          # Check if gomplate.yaml exists (the data file)
          if [ -f "gomplate.yaml" ]; then
            echo "gomplate data file detected"
            exit 0
          fi
          exit 1
  generate:
    command:
      - sh
      - -c
      - |
        # Process all YAML files that contain gomplate template syntax
        echo "Processing YAML files with gomplate templating..."
        
        # Find all .yaml and .yml files except gomplate.yaml itself
        find . -name "*.yaml" -o -name "*.yml" | grep -v "./gomplate.yaml" | while read yaml_file; do
          # Check if file contains gomplate template syntax
          if grep -q "{{.*}}" "$yaml_file"; then
            echo "Processing template: $yaml_file"
            # Process the file with gomplate using gomplate.yaml as data source
            gomplate -d data=./gomplate.yaml -f "$yaml_file" -o "${yaml_file}.tmp"
            # Replace original with processed version
            mv "${yaml_file}.tmp" "$yaml_file"
          fi
        done
        
        # Output all processed YAML files
        find . -name "*.yaml" -o -name "*.yml" | grep -v "./gomplate.yaml" | while read yaml_file; do
          echo "---"
          cat "$yaml_file"
        done
  preserveFileMode: false
