FROM debian:bookworm-20240110
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y && \
    apt install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    git \
    rsync && \
    cd && \
    mkdir -p /home/rsync/git && \
    cd /home/rsync/git && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY rsync.sh /usr/local/bin/rsync.sh
RUN chmod +x /usr/local/bin/rsync.sh

WORKDIR /home/rsync/git

ENTRYPOINT ["rsync.sh"]