apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: {{ (datasource "data").settings.namespaces.ingress_controllers }}
  labels:
    app: nginx-ingress
    cluster: {{ (datasource "data").cluster.name }}
    environment: {{ (datasource "data").cluster.environment }}
spec:
  replicas: {{ (datasource "data").apps.nginx_ingress.replicas }}
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
        cluster: {{ (datasource "data").cluster.name }}
    spec:
      containers:
      - name: nginx-ingress-controller
        image: {{ (datasource "data").apps.nginx_ingress.image }}:{{ (datasource "data").apps.nginx_ingress.tag }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: DEFAULT_INGRESS_CLASS
          value: {{ (datasource "data").settings.defaultingressclass | quote }}
        - name: CLUSTER_NAME
          value: {{ (datasource "data").cluster.name | quote }}
        {{- if (datasource "data").features.metrics_enabled }}
        - name: ENABLE_METRICS
          value: "true"
        {{- end }}
        resources:
          {{- if eq ((datasource "data").cluster.environment) "production" }}
          limits:
            cpu: {{ (datasource "data").settings.resources.large.limits.cpu | quote }}
            memory: {{ (datasource "data").settings.resources.large.limits.memory | quote }}
          requests:
            cpu: {{ (datasource "data").settings.resources.large.requests.cpu | quote }}
            memory: {{ (datasource "data").settings.resources.large.requests.memory | quote }}
          {{- else }}
          limits:
            cpu: {{ (datasource "data").settings.resources.ingress_controller.limits.cpu | quote }}
            memory: {{ (datasource "data").settings.resources.ingress_controller.limits.memory | quote }}
          requests:
            cpu: {{ (datasource "data").settings.resources.ingress_controller.requests.cpu | quote }}
            memory: {{ (datasource "data").settings.resources.ingress_controller.requests.memory | quote }}
          {{- end }}
