FROM debian:bookworm-20240110
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y && \
    apt install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    lib32gcc-s1 \
    curl \
    wine xvfb \
    xauth \
    locales && \
    adduser --disabled-password --gecos "" steam && \
    su steam -c 'cd && \
        mkdir -p /home/steam/steamcmd && \
        cd /home/steam/steamcmd && \
        curl -o steamcmd_linux.tar.gz "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" && \
        tar zxf steamcmd_linux.tar.gz && \
        rm steamcmd_linux.tar.gz' && \
    apt remove --purge -y curl && \
    apt autoremove -y && \
    cd /home/steam/steamcmd 

WORKDIR /home/steam/steamcmd
USER steam

COPY run_server.sh /usr/local/bin/run_server.sh

ENTRYPOINT  /home/steam/steamcmd/steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +app_update 443030 +quit && \
            export WINEARCH=win64 && \
            export WINEPREFIX=/home/steam/.wine64 && \
            xvfb-run --auto-servernum wine /home/steam/Steam/steamapps/common/'Conan Exiles Dedicated Server'/ConanSandboxServery.exe -logy