# Dockerfile.permissions

FROM nginx:mainline AS builder

# Set permissions
RUN mkdir -p /usr/share/nginx/html && \
    chown -R nginx:nginx /usr/share/nginx/html

COPY build/nginx.conf /etc/nginx/
COPY build/metrics.conf /etc/nginx/conf.d/metrics.conf
COPY build/metrics /usr/share/nginx/html

RUN chown nginx:nginx /usr/share/nginx/html/metrics

# Final Dockerfile

FROM nginxinc/nginx-unprivileged:stable-bullseye

# Copy files from the builder stage
COPY --from=builder /etc/nginx/ /etc/nginx/
COPY --from=builder /usr/share/nginx/html /usr/share/nginx/html

COPY build/generate.sh build/jq /usr/local/bin/
COPY build/docker-entrypoint.sh /

USER nginx